version: "3"
services:
  server:
    build: ./service2/
    environment:
      - PORT=8080
    networks:
      - loadbalancing

  client:
    build: ./service1/
    environment:
      - PORT=8199
    networks:
      - loadbalancing
    deploy:
      replicas: 3
    depends_on:
      - server
  
  nginx:
    build: ./nginx_service
    ports:
     - "8198:8198"
    networks:
      - loadbalancing
    depends_on:
      - client
      # - server

networks:
  loadbalancing: