version: "3"
services:
  server:
    build: ./service2/
    ports:
      - "8080:8080"
  client:
    build: ./service1/
    ports:
      - "8199:8199"
    network_mode: host
    depends_on:
      - server